site_name: OpenTelemetry tracepusher
nav:
    - Home: index.md
    - Try tracepusher: try.md
    - Usage: usage/index.md
    - Usage > Standalone Binary: usage/standalone.md
    - Usage > Python: usage/python.md
    - Usage > Docker: usage/docker.md
    - Usage > CI: usage/ci.md
    - Usage > Kubernetes Jobs and CronJobs: usage/k8sjobs.md
    - Usage > DevTools HAR File to OpenTelemetry Converter: usage/har-to-otel.md
    - Multi Span Traces: reference/multi-span-traces.md
    - Reference Pages: reference/index.md
    - FAQ: faq.md
    - Adopters: adopters.md
    - tracepusher on GitHub: https://github.com/agardnerit/tracepusher
