---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobtracers.tracers.tracepusher.github.io
spec:
  scope: Namespaced
  group: tracers.tracepusher.github.io
  names:
    kind: JobTracer
    plural: jobtracers
    singular: jobtracer
    shortNames:
      - jt
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              default: {}
              properties:
                collectorEndpoint:
                  type: string
                  default: ""
      additionalPrinterColumns:
      - name: "Collector Endpoint"
        type: string
        description: "Default collector endpoint for this JobTracer"
        jsonPath: .spec.collectorEndpoint
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobtracer-operator-cluster-role
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"]
- apiGroups: ["tracers.tracepusher.github.io"]
  resources: ["jobtracers"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobtracer-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobtracer-role-binding
subjects:
- kind: ServiceAccount
  name: jobtracer-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: jobtracer-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobtracer-operator
  labels:
    app: jobtracer-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobtracer-operator
  template:
    metadata:
      labels:
        app: jobtracer-operator
    spec:
      serviceAccountName: jobtracer-service-account
      containers:
      - name: jobtracer-operator
        image: gardnera/tracepusher:operator-v0.1.0