name: Build Binaries
on:
  workflow_dispatch:

jobs:
  win_build_binary:
    name: "[WIN] Build Self Contained Binary"
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Install Python and Pip Packages
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          cache: 'pip'
      - name: "Install Dependencies"
        run: pip install -r requirements.txt
      - name: "Build Binary"
        run: "python -m PyInstaller --onefile tracepusher.py"
      - name: "Setup git Config"
        run: >
          git config user.name "GitHub Actions Bot" &&
          git config user.email "<>"
      - name: "Add Binary to Repo"
        run: >
          git add dist/tracepusher.exe &&
          git commit -m "add tracepusher.exe" &&
          git pull &&
          git push
  linux_x64_build_binary:
    name: "[LIN x64] Build Self Contained Binary"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "feat/self-contained-binary"
      - name: Install Python and Pip Packages
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          cache: 'pip'
      - name: "Install Dependencies"
        run: pip install -r requirements.txt
      - name: "Build Binary"
        run: "python -m PyInstaller --onefile tracepusher.py"
      - name: "Rename file"
        run: "mv dist/tracepusher dist/tracepusher_linux_x64"
      - name: "Setup git Config"
        run: >
          git config user.name "GitHub Actions Bot" &&
          git config user.email "<>"
      - name: "Add Binary to Repo"
        run: >
          git add dist/tracepusher_linux_x64 &&
          git commit -m "add tracepusher_linux_x64 binary" &&
          git pull &&
          git push